### ISSUE TITLE
Complete tensorflow tutorial 

### ISSUE THREAD

**Issue by Benczus** [EKU-Summer-2021/dl-assignment-Szbzltn99#3]
As a developer,  I want to be able to see the expected outputs in the tutorial.
As a manager, I want you to present your tensorflow skills.

Tutorial: https://github.com/aamini/introtodeeplearning/blob/master/lab1/Part1_TensorFlow.ipynb

__AC__:
 - [x] complete tensorflow tutorial
 - [x] present tutorial output.
---

__Story Point:__ 1

**Comment by kadamQ** [comment]
Finished: #4
